### ISSUE TITLE
Questions about Sender (transport) `bit_rate`

### ISSUE THREAD

**Issue by garethsb** [AMWA-TV/bcp-006-02#13]
> The Sender resource SHOULD indicate the target bit rate (kilobits/second) including the transport overhead of the H.264 stream. The value is for the IP packets, so for the RTP payload format per RFC 6184, that includes the RTP, UDP and IP packet headers and the payload. The `bit_rate` integer value is expressed in units of 1000 bits per second, rounding up. The Sender's transport `bit_rate` value MUST derive from the Flow's encoding `bit_rate` value and according to the Flow's `constant_bit_rate` attribute it corresponds to a constant bit rate or a maximum bit rate.  

1. What does "MUST derive from" mean?

2. If we have Flow (codestream) `bit_rate` and separate Sender (transport) `bit_rate`, should we add `constant_bit_rate` flag also to Sender. Theoretically, perhaps a transport mapping of a (non-strict) CBR codestream produce a strict-CBR transport bit stream?

https://github.com/AMWA-TV/bcp-006-02/blob/400435c00a99f516d3f5147eb5248ed80b5ab42a/docs/NMOS%20With%20H.264.md?plain=1#L149

**Comment by alabou** [comment]
1. The Sender bitrate cannot be lower or equal to the encoding bitrate as there is an overhead ... it cannot be a random or unrelated value .. maybe "derive from" is not specific enough ...
2. The constant_bit_rate concept is well specified in the H.264 specification and applies to the Flow. The specification controlling the transport (ex ST2110-22) defines the transport behavior. I'm not sure we should add the constant_bit_rate flag for a Sender.

**Comment by garethsb** [comment]
1. I think it's a simple fact that the transport bit rate cannot be less than the codestream bit rate so I don't think this needs mentioning again after the first sentence describes transport overhead nicely already, or its own conformance language.
2. Maybe then, instead of the last sentence, something like "The transport `bit_rate` indicates a constant bit rate or a maximum bit rate depending on the `constant_bit_rate` of the associated Flow."

**Comment by alabou** [comment]
Will be resolved as:

"The Sender's transport bit_rate indicates a constant bit rate or a maximum bit rate depending on the constant_bit_rate attribute of the associated Flow."

**Comment by alabou** [comment]
resolved by PR #19
