### ISSUE TITLE
RFC 2250?

### ISSUE THREAD

**Issue by garethsb** [AMWA-TV/bcp-006-02#16]
The spec includes a section about Receivers supporting RFC 2250... but no section about RFC 2250 Senders?

**Comment by alabou** [comment]
There is not much to say for Sender other than "An H.264 Flow's behviour is dictated by the dynamic and in_band modes when there is no associated Sender." but it is actually written in an informative note ... maybe it should be normative.

**Comment by garethsb** [comment]
Ah, so you leave RFC 2250 transport Senders to a different spec... right?

> "An H.264 Flow's behviour is dictated by the dynamic and in_band modes when there is no associated Sender."

As we are already discussing in another issue, why should this be forced on all other transports?

FWIW, one of my red flags with this language is that it's saying _Flow_ behaviour is dictated by _Sender_ properties... (which begs the question, why aren't they Flow properties then?). Perhaps if we're talking about _behaviour_ we should not say "Flow" anyway, but "Encoder" or something?

**Comment by alabou** [comment]
What about changing this text:

"An H.264 Flow's behaviour is dictated by the `dynamic` and `in_band` modes when there is no associated Sender. See the Sender's (multiplexed) format specification for details."

For 

"The Sender's behaviour for multiplexed H.264 Flows is dictated by the `dynamic` and `in_band` modes. See the Sender's (multiplexed) format specification for details."

**Comment by alabou** [comment]
I used this wording finally, no longer in an informative note but in the normative text.

"For multiplexed H.264 Flows, the Sender MUST conform to the behaviour dictated by the `dynamic` and `in_band` modes described in this specification."

**Comment by garethsb** [comment]
Doesn't that mean it's impossible to define a mux transport mapping that DOES use strict or static or out of band parameter sets? Would it make sense to add "unless overriden by the transport mapping"?

**Comment by alabou** [comment]
Q1: True, under the current normative text.

Q2:  I would wait until an example of such thing exist. It seems unlikely to exist because of the implied complexity of the out of band mechanism and per-Flow behavior specification.

Do you have an example of such transport mapping?

**Comment by alabou** [comment]
resolved by PR #21 another issue covers the remaining discussion to have.
