### ISSUE TITLE
H.264/H.265 Annexes that are NOT Supported

### ISSUE THREAD

**Issue by alabou** [AMWA-TV/bcp-006-02#3]
The level of support for the H.264/H.265 standards in NMOS must indicate the annexes that are NOT supported.

It is proposed that initial support for H.264 does not include Annexe F (deprecated), Annex G (scalable video coding), Annex H (multiview video coding), Annex I (multiview and depth video coding) and Annex J (multiview and depth video with enhanced non-base view coding)

It is proposed that initial support for H.265 does not include Annex F (multi-layers extensions), Annex G (multiview high efficiency video coding), Annex H (scalable high efficiency video coding) and Annex I (3D high efficiency video coding)

The objective is to reduce the scope of adding support for H.264 and H.265 in NMOS and to focus on scenarios that are more in line with the NMOS ecosystem until user stories illustrate the requirements for such advanced features.

**Comment by garethsb** [comment]
Makes sense to me.

**Comment by alabou** [comment]
Instead of indicating the Annexes NOT supported we could as suggested by Andrew indicate that BCP-006-02/03 supports the H.264/H.265 specifications main normative clauses including those of annexes A, B, C, D and E only.

**Comment by garethsb** [comment]
Completed as described
